version: '3'
services:
  pretalx:
    image: pretalx/standalone:latest
    container_name: pretalx
    restart: unless-stopped
    depends_on:
      - redis
      - db
    environment:
      # Hint: Make sure you serve all requests for the `/static/` and `/media/` paths when debug is False. See [installation](https://docs.pretalx.org/administrator/installation/#step-7-ssl) for more information
      PRETALX_FILESYSTEM_MEDIA: /public/media
      PRETALX_FILESYSTEM_STATIC: /public/static
    ports:
      - "80:80"
    volumes:
      - ./conf/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - pretalx-data:/data
      - pretalx-public:/public
    labels:
      traefik.docker.network: "pretalxdocker"
      traefik.enable: "true"
    links:
      - "db:pretalx-db"

  db:
    image: postgres:latest
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
      - pretalx-db:/var/lib/postgresql
    environment:
      POSTGRES_DB: pretalx
      POSTGRES_USER: pretalx
      POSTGRES_PASSWORD: veryunsecureplschange

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: unless-stopped
    volumes:
      - pretalx-redis:/data

volumes:
  pretalx-db:
  pretalx-data:
  pretalx-public:
  pretalx-redis:
